name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.5.0+1
  jwt_decoder: ^2.0.1
  sensors_plus: ^6.1.1
  animated_text_kit: ^4.2.1
  shimmer: ^3.0.0
  confetti: ^0.8.0
  syncfusion_flutter_charts: ^28.2.9
  super_drag_and_drop: ^0.9.0-dev.6
  path_drawing: ^1.0.1
  dotted_border: ^2.1.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.2.0
  vibration: ^3.1.3
  fl_chart: ^0.70.2
  get: ^4.6.5
  flutter_fortune_wheel: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Semibold.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
    - family: handwriting
      fonts:
        - asset: fonts/handwriting.ttf
    - family: Source
      fonts:
        - asset: fonts/SourceSansPro-Black.otf
          weight: 400
    - family: Serif
      fonts:
        - asset: fonts/SourceSerifPro-Bold.otf
    - family: Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf

  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/LogoText.png
    - assets/coin.png
    - assets/Already.png
    - assets/get_started.png
    - assets/confetti.png
    - assets/coin_blue.png
    - assets/coin_red.png
    - assets/coin_green.png
    - assets/coin_purple.png
    - assets/coin_sky.png
    - assets/coin_yellow.png
    - assets/coin_purple.png
    - assets/half_piggy.png
    - assets/LogoText2.png
    - assets/coinwalogo.png
    - assets/gold-dollar-coin-icon-isometric-style-vector.jpg
    - assets/coinwaarrow.png
    - assets/16 (1).png
    - assets/17.png
    - assets/coin_level.png
    - assets/stacked_pig.png
    - assets/pigcoin2.png
    - assets/flatcoin.png
    - assets/coinstack.png
    - assets/scene1.png
    - assets/smallpig.png
    - assets/smalldollar.png
    - assets/wacoin.png
    - assets/pigdollarfly.png
    - assets/pigdollarsave.png
    - assets/pigwalletthink.png
    - assets/halfpig_green.png
    - assets/wallet_coin.png
    - assets/green_wa.png
    - assets/red_wa.png
    - assets/yellow_wa.png
    - assets/orange_wa.png
    - assets/pigspeech.png
    - assets/expaper.png
    - assets/bike coinwa.png
    - assets/grave.png
    - assets/coin1mask.png
    - assets/wawaghost.png
    - assets/suprisedwawa.png
    - assets/hexagon.png
    - assets/greenbut.png
    - assets/big green.png
    - assets/alarmb.png
    - assets/gradb.png
    - assets/hammerb.png
    - assets/calendarb.png
    - assets/peaceb.png
    - assets/cartb.png
    - assets/wawacalendar.png
    - assets/grad.png
    - assets/hammer.png
    - assets/calendar.png
    - assets/peace.png
    - assets/cart.png
    - assets/alarm.png
    - assets/scenario_alarm.png
    - assets/scenario_cart.png
    - assets/scenario_peace.png
    - assets/scenario_hammer.png
    - assets/scenario_grad.png
    - assets/scenario_calendar.png
    - assets/wawacoin2intro.png
    - assets/hammer.png
    - assets/savinggoal.png
    - assets/toothbrush.png
    - assets/notebook.png
    - assets/smartphone.png
    - assets/wawaphone.png
    - assets/bank.png
    - assets/applewatch.png
    - assets/eggs.png
    - assets/purse.png
    - assets/savingjar.png
    - assets/milk.png
    - assets/openhands.png
    - assets/water.png
    - assets/game.png
    - assets/debtrock.png
    - assets/coin2phone.png
    - assets/wawaTalk.png
    - assets/triangle.png
    - assets/wawaConfused.png
    - assets/wawaCoach.png
    - assets/Shopping_Icons/apple.png
    - assets/Shopping_Icons/banana.png
    - assets/Shopping_Icons/bigcart.png
    - assets/Shopping_Icons/chocolate.png
    - assets/Shopping_Icons/egg1.png
    - assets/Shopping_Icons/egg2.png
    - assets/Shopping_Icons/egg3.png
    - assets/Shopping_Icons/milk1.png
    - assets/Shopping_Icons/milk2.png
    - assets/Shopping_Icons/milk3.png
    - assets/Shopping_Icons/milk4.png
    - assets/Shopping_Icons/water1.png
    - assets/Shopping_Icons/water2.png
    - assets/Shopping_Icons/water3.png
    - assets/Shopping_Icons/paper.png
    - assets/trianglecut2.png
    - assets/supercarwawa.png
    - assets/check.png
    - assets/x.png
    - assets/Shopping_Icons/shoppingsave.png
    - assets/Coin-3/tape.png
    - assets/Coin-3/wawaCalendar.png
    - assets/Coin-3/piechart1.png
    - assets/Coin-3/piechart2.png
    - assets/Coin-3/wawaGirl1.png
    - assets/Coin-3/wawaGirl2.png
    - assets/Tapcoin.png
    - assets/Coin-4/bookshelf_pig.png
    - assets/Coin-4/bookshelf_family.png
    - assets/Coin-4/bookshelf_phone.png
    - assets/Coin-4/bookshelf_laptop.png
    - assets/Coin-4/wawaBack.png
    - assets/Coin-4/desk_open.png
    - assets/Coin-4/desk_closed.png
    - assets/Coin-4/lego1.png
    - assets/Coin-4/lego2.png
    - assets/Coin-4/lego3.png
    - assets/Coin-4/money_jar.png
    - assets/Coin-4/money_arrow.png
    - assets/Coin-4/wawaCash.png
    - assets/Coin-4/wawaJar1.png
    - assets/Coin-4/wawaJar2.png
    - assets/Coin-4/cash.png
    - assets/wheresave.png
    - assets/shakecoin.png
    - assets/phonenoglow.png
    - assets/phoneglow.png
    - assets/phonedata.png
    - assets/parentglow.png
    - assets/parentintro.png
    - assets/wawaparent.png
    - assets/bebe.png
    - assets/young.png
    - assets/old.png
    - assets/lowmoney.png
    - assets/mediummoney.png
    - assets/mostmoney.png
    - assets/defaultguy.png
    - assets/buzman.png
    - assets/defaultwoman.png
    - assets/ogwawa.png
    - assets/userdollar.png
    - assets/openwallet.png
    - assets/exbadges.png
    - assets/circleframe.png
    - assets/leaderboard/goldbar.png
    - assets/leaderboard/trophy.png
    - assets/wawaRelax.png
    - assets/wawaBag.png
    - assets/partyhatcircle.png
    - assets/paintcircle.png
    - assets/gradient.png
    - assets/3dcoin.png
    - assets/america_flag.png
    - assets/canada_flag.png
    - assets/Badges/baby.png
    - assets/Badges/early.png
    - assets/Badges/finwhiz.png
    - assets/Badges/piggybank.png
    - assets/Badges/pretty.png
    - assets/Badges/welcome.png
    - assets/smallpiggrey.png
    - assets/greenpiggy.png
    - assets/pigshelf.png
    - assets/wawaholding.png
    - assets/Unit 2/boxstuff.png
    - assets/Unit 2/dragonegg.png
    - assets/Unit 2/house_asset.png
    - assets/Unit 2/money_bag.png
    - assets/Unit 2/stocks.png
    - assets/Unit 2/wawaBook.png
    - assets/Unit 2/wawaPlant.png
    - assets/Unit 2/wawaValue.png
    - assets/Unit 2/scenario_money.png
    - assets/Unit 2/scenario_boxstuff.png
    - assets/Unit 2/baba_old.png
    - assets/Unit 2/baba_young.png
    - assets/Unit 2/liability.png
    - assets/Unit 2/pencil_case.png
    - assets/Unit 2/red_marker.png
    - assets/Unit 2/red_marker_faded.png
    - assets/Unit 2/fancypig.png
    - assets/Unit 2/Icon.png
    - assets/Unit 2/daboss.png
    - assets/Unit 2/namecard.png
    - assets/blackhouse.png
    - assets/blackhouse2.png
    - assets/badmilk.png
    - assets/dragonegghatch.png
    - assets/assetchart.png
    - assets/cartonmilk.png
    - assets/spillmilk.png
    - assets/yplant.png
    - assets/smallcar.png
    - assets/icecream.png
    - assets/tradingcard.png
    - assets/painting.png
    - assets/rarecoin.png
    - assets/apple.png
    - assets/Unit 3/empty_wallet.png
    - assets/Unit 3/grad_cap.png
    - assets/Unit 3/medschool.png
    - assets/Unit 3/plan.png
    - assets/Unit 3/student_loan.png
    - assets/Unit 3/wawaBus.png
    - assets/Unit 3/wawaCar.png
    - assets/Unit 3/wawaDoctor.png
    - assets/Unit 3/white_pig.png
    - assets/apple.png
    - assets/creditcardintro.png
    - assets/wawaup.png
    - assets/evilcard.png
    - assets/cutecard.png
    - assets/creditscore.png
    - assets/cardexplain.png
    - assets/pause.png
    - assets/whatisinterest.png
    - assets/yellingwawa.png
    - assets/blank.png
    - assets/creditscore.png
    - assets/blankcreditscore.png
    - assets/Unit 3/cash_register.png
    - assets/Unit 3/cashier.png
    - assets/Unit 3/credit_card.png
    - assets/Unit 3/credit_score_600.png
    - assets/Unit 3/debit_machine.png
    - assets/Unit 3/movie_seat.png
    - assets/Unit 3/wawaMovie.png
    - assets/busbob.png
    - assets/regrob.png
    - assets/studsam.png
    - assets/magichat.png
    - assets/buscard.png
    - assets/stucard.png
    - assets/magicwawa.png
    - assets/magichat.png
    - assets/wawasign.png

    # Corrected CoinWa Assets
    - assets/Ellipse_64.png
    - assets/Ellipse_64_1.png
    - assets/Ellipse_65.png
    - assets/welcome_to.png
    - assets/OFFICIAL_COINWA_LOGO.png
    - assets/dropCoin.png
    - assets/banky.png
    - assets/banky2.png
    - assets/welcome_background.png
    - assets/create_account-removebg-preview.png
    - assets/login-removebg-preview.png
    - assets/Welcome_to_1.png
    - assets/home_page.png
    - assets/coinwa_big_pig.png
    - assets/Frame_34276-removebg-preview.png
    - assets/Im_Not_New.png
    - assets/wawa.png
    - assets/slight_fire_wawa.png
    - assets/fire_wawa.png
    - assets/very_fire_wawa.png
    - assets/ice_wawa.png
    - assets/confet_coin.png
    - assets/party_wawa.png
    - assets/end_page_background.png
    - assets/profileback.png
    - assets/sounds/coin_drop.mp3
    - assets/sounds/confetti.mp3
    - assets/world.png
    - assets/weekstreakback.png
    - assets/streakpopback.png
    - assets/trophy_background.png
    - assets/signupwawa.png
    - assets/hello2frame.png
    - assets/forgotwawa.png
    - assets/mystery_box.png
    - assets/wawahand.png
    - assets/cityroad.png
    - assets/books.png
    - assets/building.png
    - assets/wawadriving.png
    - assets/wawasale.png
    - assets/wawatax.png
    - assets/hospital.png
    - assets/school.png
    - assets/police.png
    - assets/busstop.png
    - assets/tax.png
    - assets/heart.png
    - assets/police_badge.png
    - assets/house.png
    - assets/government.png
    - assets/plant.png
    - assets/mystery.png
    - assets/corporatewawa.png
    - assets/globe.png
    - assets/coin17headercash.png
    - assets/richtextriangle.png
    - assets/richwawa.png
    - assets/richwawahandmoney.png
    - assets/wawaandrichwawa.png
    - assets/taxhitlist.png
    - assets/income.png
    - assets/moneyrain.png
    - assets/bracket1coin.png
    - assets/bracket2coin.png
    - assets/bracket3coin.png
    - assets/bracket4coin.png
    - assets/bracket5coin.png
    - assets/longsky.png
    - assets/longladder.png
    - assets/ladderwawa.png
    - assets/desk.png
    - assets/boogle.png
    - assets/wawa-mail.png
    - assets/wawabadtax.png
    - assets/tax-form.png
    - assets/circled.png
    - assets/scattered-papers.png
    - assets/controller.png
    - assets/redx.png
    - assets/laptop.png
    - assets/letter.png
    - assets/document-boogle.png
    - assets/file-boogle.png
    - assets/letter-old.png
    - assets/tax-desk.png
    - assets/govern.png
    - assets/construction.png
    - assets/creditCardCoin.png
    - assets/TaxCoin.png
    - assets/wheelstand.png
    - assets/calling_wawa.png
    - assets/telephone_icon.png
    - assets/wondering_detective_wawa.png
    - assets/treasure_map.png
    - assets/supercar_dark_wawa.png
    - assets/magnifying_detective_wawa.png
    - assets/wondering_detective_wawa.png
    - assets/wawa_talking.png
    - assets/beach_background.png
    - assets/pink_piggy.png
    - assets/treasure_bottle.png
    - assets/bird_mail.png
    - assets/receipt.png
